site_name: ToolFront
site_description: Data Retrieval for AI agents
site_url: https://docs.toolfront.ai
repo_url: https://github.com/kruskal-labs/toolfront
repo_name: kruskal/toolfront

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/img/logo.svg
  favicon: assets/img/favicon.png
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    # - navigation.expand
    # - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.tabs.sticky
    # - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - search.suggest
    - announce.dismiss
    - navigation.tracking
    - navigation.prune

plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#10a2b4"
        color: "#ffffff"
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false
            show_bases: false
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_root_heading: true
            show_root_full_path: false


nav:
  - index.md
  - Documentation:
    - Browser: reference/browser.md  
    - AI Models: 
      - documentation/ai_models/index.md
      - OpenAI: documentation/ai_models/openai.md
      - Anthropic: documentation/ai_models/anthropic.md
      - Google: documentation/ai_models/google.md
      - Bedrock: documentation/ai_models/bedrock.md
      - Cohere: documentation/ai_models/cohere.md
      - Groq: documentation/ai_models/groq.md
      - Mistral: documentation/ai_models/mistral.md
      - HuggingFace: documentation/ai_models/huggingface.md
      - xAI: documentation/ai_models/xai.md
      - DeepSeek: documentation/ai_models/deepseek.md
      - Azure AI: documentation/ai_models/azure.md
      - Fireworks AI: documentation/ai_models/fireworks.md
      - Moonshot AI: documentation/ai_models/moonshot.md
      - GitHub Models: documentation/ai_models/github.md
      - Heroku AI: documentation/ai_models/heroku.md
      - OpenRouter: documentation/ai_models/openrouter.md
      - Ollama: documentation/ai_models/ollama.md
      - Together AI: documentation/ai_models/together.md
    # - Documentation:
    #   - Environments: documentation/environments.md
    #   - Browser: documentation/browser.md
    #   - AI Models: 
    #     - documentation/ai_models/index.md
    #     - OpenAI: documentation/ai_models/openai.md
    #     - Anthropic: documentation/ai_models/anthropic.md
    #     - Google: documentation/ai_models/google.md
    #     - Bedrock: documentation/ai_models/bedrock.md
    #     - Cohere: documentation/ai_models/cohere.md
    #     - Groq: documentation/ai_models/groq.md
    #     - Mistral: documentation/ai_models/mistral.md
    #     - HuggingFace: documentation/ai_models/huggingface.md
    #     - xAI: documentation/ai_models/xai.md
    #     - DeepSeek: documentation/ai_models/deepseek.md
    #     - Azure AI: documentation/ai_models/azure.md
    #     - Fireworks AI: documentation/ai_models/fireworks.md
    #     - Moonshot AI: documentation/ai_models/moonshot.md
    #     - GitHub Models: documentation/ai_models/github.md
    #     - Heroku AI: documentation/ai_models/heroku.md
    #     - OpenRouter: documentation/ai_models/openrouter.md
    #     - Ollama: documentation/ai_models/ollama.md
    #     - Together AI: documentation/ai_models/together.md
    # - Databases:
    #   - BigQuery: documentation/databases/bigquery.md
    #   - ClickHouse: documentation/databases/clickhouse.md
    #   - Databricks: documentation/databases/databricks.md
    #   - Druid: documentation/databases/druid.md
    #   - DuckDB: documentation/databases/duckdb.md
    #   - Flink: documentation/databases/flink.md
    #   - MSSQL: documentation/databases/mssql.md
    #   - MySQL: documentation/databases/mysql.md
    #   - Oracle: documentation/databases/oracle.md
    #   - PostgreSQL: documentation/databases/postgresql.md
    #   - PySpark: documentation/databases/pyspark.md
    #   - RisingWave: documentation/databases/risingwave.md
    #   - Snowflake: documentation/databases/snowflake.md
    #   - SQLite: documentation/databases/sqlite.md
    #   - Trino: documentation/databases/trino.md
    # - MCP: documentation/mcp.md
    - CLI Commands: 
        - reference/commands/browser.md
        - reference/commands/database.md
        - reference/commands/document.md    
  - Examples:
    - examples/document_rag.md
    - examples/text2sql.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/custom.css
  - https://unpkg.com/aos@2.3.1/dist/aos.css
  - https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css

extra_javascript:
  - assets/js/gtag-init.js
  - https://unpkg.com/aos@2.3.1/dist/aos.js
  - https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js
  - assets/js/marquee.js
  - assets/js/analytics.js

extra:
  generator: false
  analytics:
    provider: google
    property: G-EH352HTY05
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rRyM7zkZTf
      name: Join our Discord community
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/toolfront
      name: Follow us on X (Twitter)
    - icon: fontawesome/brands/github
      link: https://github.com/kruskal-labs/toolfront
      name: Star us on GitHub

copyright: Copyright &copy; 2025 Kruskal Labs, Inc.
