site_name: ToolFront
site_description: Build AI applications in Markdown
site_url: https://docs.toolfront.ai
repo_url: https://github.com/statespace-tech/toolfront
repo_name: statespace-tech/toolfront

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/git-alt
  logo: assets/images/logo_bw.svg
  favicon: assets/images/favicon.png
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - search.suggest
    - announce.dismiss
    - navigation.tracking
    - navigation.prune

plugins:
  - search
  - social:
      cards: false
      cards_layout_options:
        background_color: "#10a2b4"
        color: "#ffffff"
        logo: docs/assets/images/logo_bw.png
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false
            show_bases: false
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_root_heading: true
            show_root_full_path: false


nav:
  - Quickstart: index.md
  - Documentation: pages/documentation.md
  - ToolFront Cloud: pages/toolfront_cloud.md
  - FAQ: pages/faq.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/gtag-init.js
  - assets/js/analytics.js

extra:
  generator: false
  analytics:
    provider: google
    property: G-EH352HTY05
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rRyM7zkZTf
      name: Join our Discord community
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/statespace_ai
      name: Follow us on X (Twitter)
    - icon: fontawesome/brands/github
      link: https://github.com/statespace-tech/toolfront
      name: Star us on GitHub

copyright: Copyright &copy; 2025 Statespace AI, Inc.
